package varun.com.studentmanagementsystemsample.constants;

/**
 * Created by VarunBarve on 12/05/2016.
 */
public class Constants {

    public static final String TAG = "INTELEKT APP";

    public static final String KEY_STATUS_CODE = "StatusCode";
    public static final String KEY_MESSAGE = "Message";
    public static final String KEY_OBJ_LOGIN_RESULT = "LoginResult";
    public static final String KEY_OBJ_CHILD_RESULT = "objChildResult";
    public static final String KEY_ATTENDANCE_DETAIL = "attendanceDetail";
    public static final String KEY_USER_ID = "userID";
    public static final String KEY_USER_NAME = "userName";
    public static final String KEY_PASSWORD = "password";
    public static final String KEY_ROLE_ID = "roleId";
    public static final String KEY_USER_TYPE = "userTypeID";
    public static final String KEY_STUDENT_ID = "studentRegID";
    public static final String KEY_STUDENT_FIRST_NAME = "studentFirstName";
    public static final String KEY_SCHOOL_ID = "schoolID";
    public static final String KEY_AVG_ATTENDANCE = "avrageAttendance";
    public static final String KEY_AVG_PERFORMANCE = "avragePerformance";
    public static final String KEY_ATTENDANCE_RESULT = "AttendanceResult";
    public static final String KEY_ATTENDANCE_DATE = "attendanceDate";
    public static final String KEY_ATTENDANCE_STATUS = "attendanceStatus";
    public static final String KEY_CLASS_ID = "classID";
    public static final String KEY_EVENT_RESULT = "EventResult";
    public static final String KEY_EVENT_START_DATE = "startDate";
    public static final String KEY_EVENT_END_DATE = "endDate";
    public static final String KEY_EVENT_TITLE = "title";
    public static final String KEY_EVENT_DESCRIPTION = "description";
    public static final String KEY_PERFORMANCE_PROFILE = "Profile";
    public static final String KEY_PERFORMANCE_STUDENT_ID = "studentRegID";
    public static final String KEY_PERFORMANCE_STUDENT_CLASS = "studentClass";
    public static final String KEY_PERFORMANCE_FULL_NAME = "fullName";
    public static final String KEY_PERFORMANCE_ACADEMIC_YEAR = "academicYear";
    public static final String KEY_PERFORMANCE_FATHERS_NAME = "fathersName";
    public static final String KEY_PERFORMANCE_MOTHERS_NAME = "mothersName";
    public static final String KEY_PERFORMANCE_ADDRESS_RESIDENCE = "addressResidence";
    public static final String KEY_PERFORMANCE_ACADEMIC = "Academic";
    public static final String KEY_PERFORMANCE_TERM = "term";
    public static final String KEY_PERFORMANCE_BOARD = "board";
    public static final String KEY_PERFORMANCE_FA1 = "FA1";
    public static final String KEY_PERFORMANCE_FA2 = "FA2";
    public static final String KEY_PERFORMANCE_TOTAL_FA = "totalFA";
    public static final String KEY_PERFORMANCE_SA1 = "SA1";
    public static final String KEY_PERFORMANCE_TOTAL_FA_SA1 = "totalFASA1";
    public static final String KEY_PERFORMANCE_RANK = "rank";
    public static final String KEY_PERFORMANCE_ATTENDANCE = "Attendance";
    public static final String KEY_PERFORMANCE_TOTAL_WORKING_DAYS = "totalWorkingDays";
    public static final String KEY_PERFORMANCE_TOTAL_ATTENDANCE_OF_STUDENT = "totalAttendanceofStudent";
    public static final String KEY_PERFORMANCE_SUBJECT = "subject";
    public static final String KEY_INCIDENT_RESULT = "IncidentResult";
    public static final String KEY_INCIDENT_ID = "incidentId";
    public static final String KEY_INCIDENT_NAME = "incidentName";
    public static final String KEY_INCIDENT_CLASSIFICATION_NAME = "incidentClassificationName";
    public static final String KEY_INCIDENT_CLASSIFICATION_ID = "incidentClassificationId";
    public static final String KEY_INCIDENT_IS_ACITVE = "isActive";
    public static final String KEY_INCIDENT_SCHOOL_ID = "schoolId";
    public static final String KEY_ALLOCATED_DATE = "allocatedDate";
    public static final String KEY_DUE_DATE = "DueDate";
    public static final String KEY_ALLOCATED_TO = "allocatedTo";
    public static final String KEY_LATE_CHARGES = "lateCharges";
    public static final String KEY_AUTHOR_NAME = "authorName";
    public static final String KEY_EXTENDED_DAY = "extendedDay";
    public static final String KEY_BOOK_NAME = "bookName";
    public static final String KEY_LATE_RETURN_CHERGE_PER_DAY = "lateReturnChergePerDay";
    public static final String KEY_DEFAUL_ALLOCATED_DAY = "defaulAllocatedDay";
    public static final String KEY_MAXIMUM_NO_OF_EXTN = "maximumNoOfExtn";
    public static final String KEY_ALLOTED_EXTENSION = "allotedExtension";
    public static final String KEY_LIBRARY_RESULT = "LibraryResult";
    public static final String KEY_TODO_LIST_ID = "todoListID";
    public static final String KEY_TODO_LIST_TITLE = "title";
    public static final String KEY_TODO_LIST_DESCRIPTION = "description";
    public static final String KEY_TODO_LIST_RESULT = "TodoResult";
    public static final String KEY_TIME_TABLE_RESULT = "TimeTableResult";
    public static final String KEY_TIME_TABLE_ID = "timeTableID";
    public static final String KEY_TIME_TABLE_TERM_ID = "termID";
    public static final String KEY_TIME_TABLE_CLASS_ID = "classID";
    public static final String KEY_TIME_TABLE_DATE = "date";
    public static final String KEY_TIME_TABLE_DAY = "day";
    public static final String KEY_TIME_TABLE_PERIOD_ORDER = "periodOrder";
    public static final String KEY_TIME_TABLE_SUBJECT = "subject";
    public static final String KEY_ACADEMIC_YEAR_ID = "academicYearID";
    public static final String KEY_FEE_PAYMENT_RESULT = "FeePaymentResult";
    public static final String KEY_FEE_PAYMENT_COMPONENT = "FeeComponent";
    public static final String KEY_FEE_PAYMENT_COMPONENT_NAME = "componentName";
    public static final String KEY_FEE_PAYMENT_FEES_PAID = "feesPaid";
    public static final String KEY_FEE_PAYMENT_AMOUNT_DUE = "amountDue";
    public static final String KEY_FEE_PAYMENT_DUE_DATE = "dueDate";
    public static final String KEY_FEE_PAYMENT_TOTAL_FEES = "totalFees";
    public static final String KEY_FEE_PAYMENT_TOTAL_FEES_PAID = "totalFeesPaid";
    public static final String KEY_SCHOLASTIC_RESULT = "ScholasticResult";
    public static final String KEY_COSCHOLASTIC_RESULT = "CoScholasticResult";
    public static final String KEY_COSCHOLASTIC_LIST_RESULT = "CoScholasticListResult";
    public static final String KEY_TYPE_DESC = "typeDesc";
    public static final String KEY_DESCRIPTION = "description";
    public static final String KEY_REMARK = "remark";
    public static final String KEY_GRADE = "grade";
    public static final String KEY_HEALTH_RESULT = "HealthResult";
    public static final String KEY_HIEGHT = "hieght";
    public static final String KEY_WEIGHT = "weight";
    public static final String KEY_BLOODGROUP = "bloodGroup";
    public static final String KEY_DENTAL = "dental";
    public static final String KEY_VISION_LEFT = "visionLeft";
    public static final String KEY_VISION_RIGHT = "visionRight";
    public static final String KEY_SELF_AWARENESS_RESULT = "SelfAwarenessResult";
    public static final String KEY_GOAL = "goal";
    public static final String KEY_STRENGTH = "strength";
    public static final String KEY_INTEREST_HOBBIES = "interestHobbies";
    public static final String KEY_RESPONSIBILITY_DISCHARGED_EXCEPTIONAL_ACHIEVEMENTS = "responsibilityDischarged_exceptionalAchievements";
    public static final String KEY_INCIDENT_CLASSIFICATION_RESULT = "IncidentClassificationMasterResult";
    public static final String KEY_USER_SPECIFIC_ID = "userSpecificID";
    public static final String KEY_SECTION_ID = "sectionID";
    public static final String KEY_STATUS = "status";
    public static final String KEY_IMAGE_GALLERY_RESULT = "ImageGalleryResult";
    public static final String KEY_ALBUM_ID = "albumID";
    public static final String KEY_ALBUM_TITLE = "albumTitle";
    public static final String KEY_ALBUM_DESCRIPTION = "albumDescription";
    public static final String KEY_ALBUM_CREATION_DATE = "albumCreationDate";
    public static final String KEY_IMAGES = "images";
    public static final String KEY_IMAGE_ID = "imageID";
    public static final String KEY_IMAGE_TITLE = "imageTitle";
    public static final String KEY_IMAGE_DESCRIPTION = "imageDescription";
    public static final String KEY_IMAGE_TAKEN_DATE = "imageTakenDate";
    public static final String KEY_IMAGE_PATH = "imagePath";
    public static final String KEY_ID = "id";
    public static final String KEY_VALUE = "value";
    public static final String KEY_DT_CREATED= "dtCreated";


    //STATUS CODE DESC
    public static final int STATUS_CODE_SUCCESS = 0;
    public static final int STATUS_CODE_RECORD_INSERTED_SCCESSFULLY = 1;
    public static final int STATUS_CODE_ALREADY_EXISTS = 2;
    public static final int STATUS_CODE_DELETED_SUCCESSFULLY = 3;
    public static final int STATUS_CODE_UPDATED_SUCCESSFULLY = 4;
    public static final int STATUS_CODE_NO_RECORD_FOUND = 5;
    public static final int STATUS_CODE_NO_USER_INFO = 6;
    public static final int STATUS_CODE_SEARCH_TEXT = 7;
    public static final int STATUS_CODE_INTERNAL_ERROR = -1;

    //USER TYPE DESC
    public static final int USER_TYPE_PARENT = 1;
    public static final int USER_TYPE_TEACHER = 2;
    public static final int USER_TYPE_STUDENT = 3;

}
